import { createApi } from '@reduxjs/toolkit/query/react';
import { graphqlRequestBaseQuery } from '@rtk-query/graphql-request-base-query';
import { GraphQLClient } from 'graphql-request';

const client = new GraphQLClient('https://api.github.com/graphql', {
  headers: {
    Authorization: `Token ${import.meta.env.VITE_GITHUB_TOKEN}`,
  },
});

/** Base RTK Query API used in autogenerated GitHub API */
export const baseGithubApi = createApi({
  baseQuery: graphqlRequestBaseQuery({ client }),
  endpoints: () => ({}),
});
